version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 1,15 * *"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-updates:
        applies-to: version-updates
        patterns: ["*"]
      security:
        applies-to: security-updates
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 1,15 * *"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 1
    groups:
      actions:
        applies-to: version-updates
        patterns: ["*"]
      actions-security:
        applies-to: security-updates
        patterns: ["*"]
    commit-message:
      prefix: "ci(deps)"
    labels:
      - "dependencies"
