# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
    ignore_title_keywords:
      - WIP
      - "DO NOT MERGE"
  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/coverage/**"
    - "!**/.docusaurus/**"
    - "!**/yarn.lock"
chat:
  auto_reply: true
