#!/bin/bash

update_dependencies() {
  echo 'updating dependencies' &&
  npm update --silent
}

update_version() {
  current_tag=$(git describe --abbrev=0 --tags) &&
  echo 'bump from '$current_tag' to '$1 &&
  sed -i "s/\(version\":[ ]*\"\)$current_tag/\1$1/" package.json
}

build() {
  echo 'building' &&
  npm run build --silent &&
  echo 'building' &&
  npm run release --silent
}

git_push() {
  echo 'pushing to github' &&
  git add package.json dash-shaka-playback.js &&
  git commit -m 'bump to '$1 &&
  git tag $1 &&
  git push
  git push --tags
}

npm_publish() {
  npm publish
}

main() {
  update_dependencies &&
  update_version $1 &&
  build
  if (("$?" != "0")); then
    echo "something failed during dependency update, version update, or build"
    exit 1
  fi
  if (("$?" == "0")); then
    git_push $1 &&
    npm_publish &&
    exit 0

    echo "something failed"
    exit 1
  else
    echo "you broke the tests. fix it before bump another version."
    exit 1
  fi
}

if [ "$1" != "" ]; then
  main $1
else
  echo "Usage: bump [new_version]"
fi
