name: Question
description: Need help with something not related to a Bug or Feature Request?
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: What do you want to do with Clappr?
    validations:
      required: true
  - type: textarea
    id: what_tried_so_far
    attributes:
      label: What have you tried so far?
    validations:
      required: false
