name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: install node
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: install dependencies
        run: yarn

      - name: run lint
        run: yarn lint

      - name: run unit tests
        run: yarn test

      - name: build
        run: yarn build

      - name: build dist
        run: yarn build:dist
